const TicketValidator = require("../../../validators/Ticket/TicketValidators");  // Import the Joi validation for Ticket
const Ticket = require("../../../models/Ticket");  // Import the Mongoose model for Ticket

async function createTicket(req, res) {
    try {
      // Validate the request body using Joi
      const { error } = TicketValidator(req.body);
  
      if (error?.details?.length) {
        const errorMessages = error.details.map((err) => err.message).join(", ");
        return res.status(400).json({ message: errorMessages });
      }
  
      // Destructure the ticket data from the request body (without ticket_code)
      const { title, employee_name, priority, description, attachment, status, end_date } = req.body;
  
      // Create a new ticket instance (ticket_code will be auto-generated by mongoose-sequence)
      const newTicket = new Ticket({
        title,
        employee_name,
        priority,
        description,
        attachment,
        status: status || "close",  // Default to 'close' if not provided
        end_date: end_date || Date.now(),  // Use the provided end date or default to current date
      });
  
      // Save the ticket to the database
      await newTicket.save();
  
      return res.status(201).json({
        message: "Ticket created successfully!",
        ticket: newTicket,
        hasError: false,
      });
    } catch (error) {
      console.error("Error creating ticket:", error);
      return res.status(500).json({
        message: "Failed to create ticket.",
        error: error.message,
      });
    }
  }
  
  
  module.exports = createTicket;
// controllers/Ticket/index.js
// const TicketValidator = require("../../../validators/Ticket/TicketValidators");
// const Ticket = require("../../../models/Ticket");
// const upload = require('../../../middleware/upload');
// createTicket = async (req, res) => {
//     try {
//       const { title, employee_name, priority, description, status, end_date } = req.body;
  
//       // Validate data using Joi
//       const { error } = TicketValidator.validate(req.body);
//       if (error) {
//         return res.status(400).json({ message: error.details[0].message, hasError: true });
//       }
  
//       // Get the uploaded file URL (if any)
//       const attachment = req.file ? req.file.location : null; // If file uploaded, get the file URL
  
//       // Save the ticket to the database
//       const newTicket = new Ticket({
//         title,
//         employee_name,
//         priority,
//         description,
//         status: status || 'close',
//         end_date,
//         attachment, // Save the URL of the uploaded file
//       });
  
//       await newTicket.save();
  
//       return res.status(201).json({
//         message: 'Ticket created successfully!',
//         ticket: newTicket,
//         hasError: false,
//       });
//     } catch (err) {
//       console.error(err);
//       return res.status(500).json({ message: 'Error creating ticket.', hasError: true });
//     }
//   };
  
//   module.exports = createTicket;